-- Seed educational content for key matrix cells
INSERT INTO educational_content (cell_row, cell_column, content_type, title, content, sort_order) VALUES
('devices', 'identify', 'overview', 'Device Asset Management', 'Maintaining a comprehensive inventory of all hardware assets is the foundation of device security. This includes servers, workstations, mobile devices, IoT devices, and network equipment.', 1),
('devices', 'protect', 'overview', 'Device Hardening', 'Apply security controls to protect device integrity including endpoint protection, configuration management, encryption, and access controls.', 1),
('devices', 'detect', 'overview', 'Endpoint Detection', 'Monitor devices for signs of compromise, anomalous behavior, and policy violations using EDR, host-based IDS, and behavioral analytics.', 1),
('devices', 'respond', 'overview', 'Incident Response for Devices', 'Contain and remediate device compromises through isolation, forensic analysis, and automated response playbooks.', 1),
('devices', 'recover', 'overview', 'Device Recovery', 'Restore compromised devices to known-good states through backup restoration, reimaging, and validated recovery procedures.', 1),
('applications', 'identify', 'overview', 'Application Inventory', 'Discover and catalog all applications including custom, commercial, SaaS, and shadow IT applications across the organization.', 1),
('applications', 'protect', 'overview', 'Application Security', 'Implement security controls within and around applications including WAF, SAST/DAST testing, API security, and secure SDLC practices.', 1),
('applications', 'detect', 'overview', 'Application Threat Detection', 'Monitor applications for vulnerabilities, attacks, and anomalous behavior using RASP, log analysis, and application-level IDS.', 1),
('applications', 'respond', 'overview', 'Application Incident Response', 'Respond to application-level incidents including patching, virtual patching, and application-specific containment measures.', 1),
('applications', 'recover', 'overview', 'Application Recovery', 'Restore application functionality after incidents through rollback, redeployment, and data recovery procedures.', 1),
('networks', 'identify', 'overview', 'Network Discovery', 'Map and inventory all network assets, segments, and connections to understand the full network topology and attack surface.', 1),
('networks', 'protect', 'overview', 'Network Protection', 'Implement network security controls including firewalls, segmentation, VPNs, zero-trust architecture, and encryption.', 1),
('networks', 'detect', 'overview', 'Network Monitoring', 'Monitor network traffic for threats, intrusions, and anomalous activity using NDR, IDS/IPS, NetFlow analysis, and DNS monitoring.', 1),
('networks', 'respond', 'overview', 'Network Incident Response', 'Contain network threats through traffic blocking, segment isolation, and coordinated response across network infrastructure.', 1),
('networks', 'recover', 'overview', 'Network Recovery', 'Restore network operations after incidents through failover, redundancy activation, and network rebuilding procedures.', 1),
('data', 'identify', 'overview', 'Data Classification', 'Discover, classify, and inventory sensitive data across all storage locations including databases, file shares, cloud storage, and endpoints.', 1),
('data', 'protect', 'overview', 'Data Protection', 'Implement data protection controls including encryption at rest and in transit, DLP, access controls, data masking, and backup procedures.', 1),
('data', 'detect', 'overview', 'Data Breach Detection', 'Monitor for unauthorized data access, exfiltration attempts, and data integrity violations using DLP, UEBA, and database activity monitoring.', 1),
('data', 'respond', 'overview', 'Data Breach Response', 'Respond to data breaches through containment, notification procedures, forensic investigation, and regulatory compliance.', 1),
('data', 'recover', 'overview', 'Data Recovery', 'Recover lost or corrupted data through backup restoration, data reconstruction, and integrity verification procedures.', 1),
('users', 'identify', 'overview', 'Identity Management', 'Establish and manage user identities, roles, and access rights across the organization using IAM, directory services, and governance.', 1),
('users', 'protect', 'overview', 'User Protection', 'Protect user accounts through MFA, SSO, privileged access management, security awareness training, and strong authentication policies.', 1),
('users', 'detect', 'overview', 'User Behavior Analytics', 'Detect compromised accounts and insider threats through UEBA, impossible travel detection, and anomalous access pattern monitoring.', 1),
('users', 'respond', 'overview', 'User Incident Response', 'Respond to account compromises through credential reset, session termination, access revocation, and user notification procedures.', 1),
('users', 'recover', 'overview', 'User Access Recovery', 'Restore user access after incidents through identity verification, credential reissuance, and access restoration procedures.', 1);
